CREATE TABLE especialidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(8) NOT NULL UNIQUE,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    telefono VARCHAR(9) NOT NULL,
    correo VARCHAR(100) NOT NULL UNIQUE,
    direccion VARCHAR(255),
    alergias VARCHAR(500),
    historial_medico VARCHAR(1000),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE medicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    cmp VARCHAR(10) NOT NULL UNIQUE,
    especialidad_id BIGINT NOT NULL REFERENCES especialidades(id),
    telefono VARCHAR(9) NOT NULL,
    correo VARCHAR(100) NOT NULL UNIQUE,
    horario_atencion VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    paciente_id BIGINT UNIQUE REFERENCES pacientes(id),
    medico_id BIGINT UNIQUE REFERENCES medicos(id),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    ultimo_acceso TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_usuario_vinculo CHECK ((rol = 'ADMIN' AND paciente_id IS NULL AND medico_id IS NULL) OR (rol = 'PACIENTE' AND paciente_id IS NOT NULL AND medico_id IS NULL) OR (rol = 'MEDICO' AND medico_id IS NOT NULL AND paciente_id IS NULL))
);

CREATE TABLE citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL REFERENCES pacientes(id),
    medico_id BIGINT NOT NULL REFERENCES medicos(id),
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    estado VARCHAR(20) NOT NULL,
    prioridad VARCHAR(20) NOT NULL,
    motivo_consulta VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_cita_medico_fecha UNIQUE (medico_id, fecha_hora)
);
CREATE INDEX idx_citas_paciente_fecha ON citas (paciente_id, fecha_hora DESC);
CREATE INDEX idx_citas_medico_fecha ON citas (medico_id, fecha_hora DESC);

CREATE TABLE consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id BIGINT NOT NULL UNIQUE REFERENCES citas(id),
    diagnostico VARCHAR(1000) NOT NULL,
    tratamiento VARCHAR(1000) NOT NULL,
    observaciones VARCHAR(500),
    fecha_atencion TIMESTAMP WITH TIME ZONE NOT NULL
);
