export const colors = {
  primary: '#006591',
  'primary-container': '#0ea5e9',
  'on-primary': '#ffffff',
  'on-primary-container': '#003751',
  'inverse-primary': '#89ceff',
  'primary-fixed': '#c9e6ff',
  'primary-fixed-dim': '#89ceff',
  'on-primary-fixed': '#001e2f',
  'on-primary-fixed-variant': '#004c6e',
  secondary: '#006398',
  'on-secondary': '#ffffff',
  'on-secondary-container': '#00476e',
  'secondary-fixed': '#cce5ff',
  'secondary-fixed-dim': '#93ccff',
  'on-secondary-fixed': '#001d31',
  'on-secondary-fixed-variant': '#004b73',
  tertiary: '#006c49',
  'on-tertiary': '#ffffff',
  'tertiary-container': '#00b17b',
  'on-tertiary-container': '#003b26',
  'tertiary-fixed': '#6ffbbe',
  'tertiary-fixed-dim': '#4edea3',
  'on-tertiary-fixed': '#002113',
  'on-tertiary-fixed-variant': '#005236',
  error: '#ba1a1a',
  'on-error': '#ffffff',
  'error-container': '#ffdad6',
  'on-error-container': '#93000a',
  surface: '#f6faff',
  'surface-container': '#eaeef4',
  'surface-container-high': '#e4e8ee',
  'surface-container-highest': '#dee3e9',
  'surface-container-lowest': '#ffffff',
  'surface-container-low': '#f0f4fa',
  'surface-dim': '#d6dae0',
  'surface-bright': '#f6faff',
  'surface-tint': '#006591',
  'on-surface': '#171c20',
  'on-surface-variant': '#3e4850',
  'inverse-surface': '#2c3135',
  'inverse-on-surface': '#edf1f7',
  'surface-variant': '#dee3e9',
  background: '#f6faff',
  'on-background': '#171c20',
  outline: '#6e7881',
  'outline-variant': '#bec8d2',
};

export const typography = {
  'display-lg': {
    fontFamily: 'Inter',
    fontSize: '36px',
    fontWeight: 700,
    lineHeight: '44px',
    letterSpacing: '-0.02em',
  },
  'headline-lg': {
    fontFamily: 'Inter',
    fontSize: '28px',
    fontWeight: 600,
    lineHeight: '36px',
    letterSpacing: '-0.01em',
  },
  'headline-md': {
    fontFamily: 'Inter',
    fontSize: '20px',
    fontWeight: 600,
    lineHeight: '28px',
  },
  'body-lg': {
    fontFamily: 'Inter',
    fontSize: '16px',
    fontWeight: 400,
    lineHeight: '24px',
  },
  'body-md': {
    fontFamily: 'Inter',
    fontSize: '14px',
    fontWeight: 400,
    lineHeight: '20px',
  },
  'label-md': {
    fontFamily: 'Inter',
    fontSize: '12px',
    fontWeight: 600,
    lineHeight: '16px',
    letterSpacing: '0.05em',
  },
  'label-sm': {
    fontFamily: 'Inter',
    fontSize: '11px',
    fontWeight: 500,
    lineHeight: '14px',
  },
};

export const rounded = {
  sm: '0.25rem',
  DEFAULT: '0.5rem',
  md: '0.75rem',
  lg: '1rem',
  xl: '1.5rem',
  full: '9999px',
};

export const spacing = {
  base: '4px',
  xs: '4px',
  sm: '8px',
  md: '16px',
  lg: '24px',
  xl: '32px',
  'container-max': '1440px',
  gutter: '24px',
  'sidebar-expanded': '260px',
  'sidebar-collapsed': '72px',
};